before_script:
    - date
    - uname -a
    - printenv | sort

java:
    image: gpdowning/java
    script:
    - ls -al
    - cd java
    - cat Makefile
    - make versions
    - ls -al
    - make run
    - ls -al

python:
    image: gpdowning/python
    script:
    - ls -al
    - cd python
    - cat Makefile
    - make versions
    - ls -al
    - make run
    - ls -al
