before_script:
    - date
    - uname -a
    - printenv | sort

java:
    image: gpdowning/java
    script:
    - ls -al
    - cd java
    - ls -al
    - cat Makefile
    - ls -al
    - make versions
    - make run
    - ls -al

python:
    image: gpdowning/python
    script:
    - ls -al
    - cd python
    - ls -al
    - cat Makefile
    - ls -al
    - make versions
    - make run
    - ls -al

typescript:
    image: gpdowning/typescript
    script:
    - ls -al
    - cd typescript
    - ls -al
    - cat Makefile
    - npm install @types/mocha
    - npm install @types/node
    - npm install assert
    - npm install lodash
    - ls -al
    - make versions
    - make run
    - ls -al
